### ISSUE TITLE
Router specific options in YAML

### ISSUE THREAD

**Issue by qaoru** [rahveiz/topomate#1]
Add router options such as :
```yaml
autonomous_systems:
  - asn: 10
    routers:
        - hostname: 'MyRouter'
           router_id: '10.1.1.1'
           send_bgp_communities: [10, 299]
```
